### ISSUE TITLE
Update manager Mint 18.2 levels (especially for Firefox)

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/mintupdate#245]
Mint 18.2 beta Cinnamon 64 bit.

Note: The following problem is only taken from the documentation (included help file), as until now except 2 kernel updates nothing than level 2 updates have been released; so no practical tests had been possible.

I read in the documentation, that Firefox will be listed as level 3 update. I consider this as a serious security mistake.

A browser is the direct connection for the user for most accesses to the Internet. A security hole in the browser might seriously affect the system, at least the user account. So updating the browser - here: Firefox - as soon as possible is one of the most important things to do. No security advisor will put this in question.

But leveling FF to level 3 means, that those, you select the first update manager policy choice will not even see it. A very dangerous situation.

Further more I wonder, what "qualifies" FF for level 3 at all. Which other applications or which part of the system are supposed to fail, if a FF update should bring a regression? Many years of practical experience tell, that this is near to impossible to happen. In this hypothetical case it will be only FF which will fail (just as any level 1 or 2 application would possibly fail in case of a serious regression), but that is all.

Besides that one of my main activities in the support forum is to help users, who have a problem with FF. A high number of tens (perhaps more than hundred) successful support tasks tell me, that in 95 + % of all cases a problem with FF is a problem with the FF profile. It might get corrupted, there might be a wrong setting or a problematic add-on. Resetting the FF-profile is nearly always the working solution in those cases. Conclusion: There is no reason (IMHO), which qualifies FF to anything different as for level 1 or at least 2. But there are important aspects, which disqualifies FF for level 3.

Additionally you should know, that there do exist users, who believe to make a very secure choice by applying only level 1 or at most level 2. This is not my choice and I recommend users a different approach. But without possible doubt the update manager allows this. By doing a very heavily support job in the forum I know, that those users do exist and there cannot be the least doubt, that with the current level for FF they will quickly and about every 6 weeks again fall into this security trap.

**Comment by NZamp** [comment]
Firefox tagged as a level 3 update? Totally agree with the post, it's a huge security flow to leave the default web browser as an optional update (even in case that the user selects to accept only level 1 and 2 updates).

**Comment by Cos-mo** [comment]
Now after having a Firefox update available it shows, that things are even worse.

Not only shows the Firefox following the help file as level 3 update. It does not show as a security update. This means in the result, that with the new mint update level system the first policy option is a big security leak in itself.

Actually there is hardly ever a Firefox-update, which does not contain security fixes. But there come - if needed - updates which have nothing than security fixes.
For FF 54 there are more than 2 dozen security fixes listed, 4 of them are mentioned as critical.

Result: The new level system of the update manager makes things worse than ever! With the current settings for levels (and security marks) this is unacceptable.

**Comment by NZamp** [comment]
This must be something that escaped from the dev team. It's too serious for the security of the system to be left like that on purpose.

@clefebvre  **Bug**

**Comment by clefebvre** [comment]
This was an oversight. Firefox (and Thunderbird in LMDE) should always be flagged as a security update. This was fixed in https://github.com/linuxmint/mintupdate/commit/a6a033a574cea60e0e9234bec0f7a8fc33fefc1d

**Comment by Cos-mo** [comment]
The issue is **not** solved!

Besides the point, that I opened this because of the wrong level for Firefox (absolutely not understandable, why Firefox as the only browser is set there), the consequential security leak does still exist.

See this scenario. A user has set the first policy option. Now a FF security fix gets available, but no other update for level 1 or 2. Result: The update manager will show in the tray the green check mark and the user will - possibly for a number of days, not get notified about this security update. Even with the last fix the update manager results in a possibly very serious security leak.

I ask to reopen it - and of course I ask you to correct it.

More reasoning: https://forums.linuxmint.com/viewtopic.php?p=1334124#p1334124

**Comment by Pjotr123** [comment]
I understand why Firefox was flagged as level 3. But web browsers are, by far, the most attacked pieces of software of them all. Even a relatively small delay in updating this high-risk package, can have serious security consequences.

That's why I think the best balance of usability versus security would in this case be, to change its flag into level 2....

**Comment by IzzySoft** [comment]
Could it be this change had some side effects? I've just upgraded to 18.3 from 18.1, and the tray icon *always* shows there'd be updates pending. Well, that's true – but those updates are in level 4 only (and my update policy only includes everything up to level 3). So those "pending updates" are not even checked when I open the update manager (and of course they should not).

This situation leads the user to ignore the tray icon at all ("ah, it's just them level 4 ones I already know of"). So did I miss a toggle somewhere to have the tray icon only show updates according to the policy, as it was with 18.1?
