### ISSUE TITLE
A window displaying an error message extends off the bottom of the screen, needlessly

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintupdate#368]
Screenshot:
![image](https://user-images.githubusercontent.com/9998846/42664013-6de8aeaa-8630-11e8-8066-8cc6c29959a8.png)

Now, (1) Newbies may find this situation rather hard to deal with, given that the 'close' button - and, for all they know, other buttons - are hidden. (One must use alt-drag to show the whole window.) (2) As one can see from the screenshot, seemingly there is no need for the window to be so long.

I infer from 2 that this is a bug. I infer from 1 that it is an unfortunate one.

Linux Mint 19
Resolution: 2560x1440 

Cf. perhaps these reports: #354; #279.
DPI: double

**Comment by CottonEaster** [comment]
Or again:

![image](https://user-images.githubusercontent.com/9998846/43328996-46d3bdb8-91b7-11e8-8390-4b329c6c0d7a.png)

**Comment by xenopeek** [comment]
Easily reproduced and indeed annoying. You can just press Esc to close it. I'm not sure Linux Mint can fix it, this is a window from Synaptic.

**Comment by CottonEaster** [comment]
Is this fixed by a recent commit? I do not know how to test?

**Comment by joseary15** [comment]
Can you change a global "Screensize" variable to force the window to be drawn within bounds?

**Comment by CottonEaster** [comment]
I asked

> Is this fixed by a recent commit?

I can now supply the answer, which is: no. The problem persists.

@joseary15 : sorry, I do not know whether you were addressing me.

**Comment by gm10** [comment]
This is a bug with Synaptic's HiDPI support. All `mintupdate` could theoretically do is set `GDK_DPI_SCALE=0.5` when calling Synaptic in a HiDPI situation, which would prevent the window size issue, but make the text half sized, i.e. probably too small to read and thus leading to an arguably worse situation than currently. What do you think? (I don't have a HiDPI screen so I cannot easily judge this)

Otherwise we'd have to fix it in Synaptic. There have been discussions about ditching use of Synaptic in the Mint tools entirely, which would be my preferred solution by far not just to address this one but a number of related issues caused by the Synaptic integration, but no decision has been reached as of yet.

**Comment by LinuxOnTheDesktop** [comment]
I am afraid that this still happens, on Mint 19.1. The image below shows my entire (2560 x 1440, hiDPI force-enabled) screen:

![image](https://user-images.githubusercontent.com/47056543/54197135-0f6ebf00-44bb-11e9-9162-2707f2d71712.png)

**Comment by LinuxOnTheDesktop** [comment]
I have just experienced this problem with the alpha version of Mint, from the PPA. Yes, one can still navigate the window, but (1) one needs to know how, (2) there is absolutely no need for such a long window.

**Comment by JosephMcc** [comment]
I found the problem here and I'll see if we can fix it on our side

**Comment by JosephMcc** [comment]
Ok. PR'd a fix to Mint's version of synaptic for this.
